apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 1 
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: helloapp
        image: localhost:5000/hello-app:1.0
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: hello-app
  name: hello-app
  namespace: default
spec:
  selector:
    app: hello-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080